### ISSUE TITLE
debade-trigger 中 secret 应考虑针对每一个 http-jsonrpc 站点用不同的配置.

### ISSUE THREAD

**Issue by stenote** [iamfat/debade-trigger#3]
debade-trigger 中 secret 应考虑针对每一个 http-jsonrpc 站点用不同的配置.

如果 trigger 需要对多个不同的站点进行 http-jsonrpc 请求，有可能这些站点设置的 secret 是不同的。

**Comment by iamfat** [comment]
你再加一个subscriber不行吗?

**Comment by stenote** [comment]
行
