### ISSUE TITLE
debade-trigger 中 jsonrpc 的 debade-token 为啥不直接通过 jsonrpc 中的 params 中传递。

### ISSUE THREAD

**Issue by stenote** [iamfat/debade-trigger#7]
debade-trigger 中 jsonrpc 的 debade-token 发送为何通过 HEADER 发送。

本来是 jsonrpc 发送，为何不直接在 jsonrpc 的 params 中增加 _token 。专门通过 HEADER 发送过去。

**Comment by stenote** [comment]
debade-trigger 中 jsonrpc 的 debade-token 为啥不直接通过 jsonrpc 中的 params 中传递。

**Comment by iamfat** [comment]
因为那个TOKEN是为了验证这个是从一个被授权的DeBaDe Trigger调用的, 设计的时候就是对这个HTTP请求进行验证, 而不是对数据进行验证
这种在HTTP HEADER中进行安全验证的方式也比较常见, 比较典型的例子可以看一下Trello的API实现.

**Comment by stenote** [comment]
trello 的是 Restful API 啊，不是 json 的啊。

**Comment by iamfat** [comment]
我们这个是基于HTTP的JSONRPC啊... 也不是单纯的JSONRPC啊...

**Comment by iamfat** [comment]
另外Trello的数据传输是json的

**Comment by stenote** [comment]
roger that !

**Comment by iamfat** [comment]
其实这个问题倒是不在于行和不行的问题... 当时的初衷就是觉得HTTP header加额外信息比较常见, 然后不希望修改数据体本身的结构.
